controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller/
        namespace: App\Controller
    type: annotation

kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: annotation